server:
  servlet:
    context-path: /website

spring:
  application:
    name: psmp-portal-website
  datasource:
    url: jdbc:dm://localhost:5236/D5000?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: D5000
    password: 123456789
    driver-class-name: dm.jdbc.driver.DmDriver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  profiles:
    active: dev

  redis:
    cluster:
      max-redirects: 10
      nodes: 122.113.5.201:9001
    commandTimeout: 5000
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 1000
        min-idle: 50
    timeout: 3000

#mybatis-plus:
#  mapper-locations: classpath:mapper/*/*.xml
#  type-aliases-package: com.alonginfo.psmpportalwebsite.*.model
