server:
  servlet:
    context-path: /portal

spring:
  application:
    name: psmp-portal
  datasource:
    url: jdbc:dm://localhost:5236/D5000?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: D5000
    password: 123456789
    driver-class-name: dm.jdbc.driver.DmDriver
    type: com.alibaba.druid.pool.DruidDataSource

  profiles:
    active: dev
  #设置文件上传大小
  servlet:
    multipart:
      max-request-size: 1000Mb
      max-file-size: 1000Mb
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.alonginfo.psmpportal.*.model
  global-config:
    db-config:
      db-type: mysql

files:
  directory:
    filesUrl: /Resources/protal